# version: "3.9"

services:
  dashboard:
    build: ./dashboard
    ports:
      - "8000:8000"

  monitor-agent:
    build: ./monitor-agent
    depends_on:
      - dashboard

  edge-inference:
    build: ./edge-inference
    depends_on:
      - dashboard

